config/routes.rb
CookItUp::Application.routes.draw do
  root to: 'skills#index'

  get 'recipes', to: 'recipes#index'
  get 'skills', to: 'skills#index'
  get 'all_skills', to: 'skills#all_skills', as: 'all_skills'

  post 'known_recipes', to: 'recipes#display'
  post 'unknown_skills', to: 'skills#display'
  post 'unlocked_recipes', to: 'recipes#unlocked'

  get 'recipes/:id/photo_upload', to: 'recipes#new_photo', as: 'upload_recipe_photo'
  patch 'recipes/:id/photo_upload', to: 'recipes#save_photo', as: 'recipe_photo'

  get 'skills/:id/photo_upload', to: 'skills#new_photo', as: 'upload_skill_photo'
  patch 'skills/:id/photo_upload', to: 'skills#save_photo', as: 'skill_photo'
end

app/models/concerns/maper.rb
def whatever(*skill_ids)
  skill_ids.map(&:&)
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :skill
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :practices
  has_many :skills, through: :practices

  has_attached_file :photo, styles: {
      # thumb: '100x100>',
      # square: '200x200#',
      # medium: '300x300>',
      tile: '225x260^' # width by height
  }

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def self.find_recipes_that_require_any_of_these_skills(*known_skill_ids)

    # the crazy sql way (number of queries is always 2)
    Recipe.joins(:skills)
          .merge(Skill.where(id: known_skill_ids))
          .where("recipes.id NOT IN (?)", Recipe.joins(:skills).merge(Skill.where("skills.id NOT IN (?)", known_skill_ids)).uniq.pluck(:id)).uniq

    # the more-understandable ruby way (number of queries scales linearly)
    self.select do |recipe|
      recipe.skill_ids.all? do |skill_id|
        known_skill_ids.include?(skill_id)
      end
    end
  end

  # calls the above method twice, once with the new skill and once without
  # and subtracts one result from the other
  # this is also the hackiest thing ever
  def self.find_newly_unlocked_recipes(*all_skill_ids)
    all_skill_ids.delete(0)
    new_skill_id = all_skill_ids.last
    all_skill_ids.delete(all_skill_ids.last)
    prior_skill_ids = all_skill_ids
    self.find_recipes_that_require_any_of_these_skills(*(prior_skill_ids + [new_skill_id])) - self.find_recipes_that_require_any_of_these_skills(*prior_skill_ids)
  end

  # this is an instance method, called on a single recipe
  # therefore it's not .self
  def photo_url
    self.photo.url(:tile) # but now, self is the recipe
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :practices
  has_many :recipes, through: :practices

  has_attached_file :photo, styles: {
      # thumb: '100x100>',
      # square: '200x200#',
      # medium: '300x300>',
      block: '1000x300^' # width by height
    }

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  def photo_url
    self.photo.url(:block)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def home
  end

  def index
    @recipes = Recipe.order(id: :asc)
  end

  def display
    # this is the hackiest hack ever, but i can't think of another way to keep these numbers as pure integers without turning them into an array or a string, neither of which are parseable
    @recipes = Recipe.find_recipes_that_require_any_of_these_skills(
      params[:known_skills][0].to_i,
      params[:known_skills][1].to_i,
      params[:known_skills][2].to_i,
      params[:known_skills][3].to_i,
      params[:known_skills][4].to_i)
    render json: @recipes.to_json(only: [:id, :name, :url, :photo], methods: [:photo_url])
  end

  def unlocked
    @recipes = Recipe.find_newly_unlocked_recipes(
      params[:known_skills][0].to_i,
      params[:known_skills][1].to_i,
      params[:known_skills][2].to_i,
      params[:known_skills][3].to_i,
      params[:known_skills][4].to_i)
    render json: @recipes.to_json(only: [:id, :name, :url, :photo], methods: [:photo_url])
  end

  def new_photo
    @recipe = Recipe.find(params[:id])
  end

  def save_photo
    @recipe = Recipe.find(params[:id])
    @recipe.update_attributes(photo: params[:recipe][:photo])
    @recipe.save
    redirect_to recipes_path
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index
    @skills = Skill.all
  end

  def display
    @skills = Skill.find(params[:unknown_skills])
    render json: @skills.to_json(only: [:id, :name, :url, :photo], methods: [:photo_url])
  end

  def new_photo
    @skill = Skill.find(params[:id])
  end

  def save_photo
    @skill = Skill.find(params[:id])
    @skill.update_attributes(photo: params[:skill][:photo])
    @skill.save
    redirect_to all_skills_path
  end

  def all_skills
    @skills = Skill.order(id: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookItUp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1 class="text-center"><span>Cook</span><span>It</span><span>Up</span></h1>

<%= yield %>

</body>
</html>

app/views/recipes/home.html.erb
<h2>Oh hai thear!</h2>

<h3><%= link_to "Get Started", skills_path %></h3>

<h3><%= link_to "See All Recipes", recipes_path %></h3>

<h3><%= link_to "See All Skills", all_skills_path %></h3>

app/views/recipes/index.html.erb
<h2>All Recipes</h2>

<table class="table">

  <tr>
    <th>Name</th>
    <th>Skills</th>
    <th>URL</th>
    <th>Photo</th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= recipe.skills.map { |skill| skill.name }.join(", ") %></td>
      <td><a href="<%= recipe.url %>"><%= recipe.url.truncate(50) %></a></td>
      <td>
        <%= image_tag recipe.photo.url(:tile), class: "photo-preview" %> <br>
        <%= link_to "Upload photo", upload_recipe_photo_path(recipe) %>
      </td>
    </tr>
  <% end %>

</table>

app/views/recipes/new_photo.html.erb
<h2><%= @recipe.name %></h2>

<h2>Upload a Photo</h2>

<%= form_for @recipe, url: photo_path, html: { method: :patch } do |f| %>
<%= f.label :photo %>
<%= f.file_field :photo %>
<br><br>
<%= f.submit %>
<% end %>

app/views/skills/all_skills.html.erb
<h2>All Skills</h2>

<table class="table">

  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Photo</th>
  </tr>

  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.name %></td>
      <td><a href="<%= skill.url %>"><%= skill.url.truncate(50) %></a></td>
      <td>
        <%= image_tag skill.photo_url, class: "photo-preview" %> <br>
        <%= link_to "Upload photo", upload_skill_photo_path(skill) %>
      </td>
    </tr>
  <% end %>

</table>

app/views/skills/index.html.erb
<div class="container text-center">

  <div id="all-skills">
    <h2 id="instructions">Select the skills you already know</h2>

    <% @skills.each do |skill| %>
      <div class="skill-div">
        <button type="button" class="skill-button btn btn-lg btn-primary" id="<%= skill.name.downcase %>-button" data-skill-id="<%= skill.id %>"><%= skill.name %></button>
      </div>
    <% end %>

    <button type="button" class="btn btn-block btn-lg btn-danger" id="skills-done-button">Let's Cook!</button>
  </div>

</div>

app/views/skills/new_photo.html.erb
<h2><%= @skill.name %></h2>

<h2>Upload a Photo</h2>

<%= form_for @skill, url: skill_photo_path, html: { method: :patch } do |f| %>
<%= f.label :photo %>
<%= f.file_field :photo %>
<br><br>
<%= f.submit %>
<% end %>